<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="${base_length/2-0.05/2} 0 ${base_height/2+0.01/2}" rpy="0 0 0"/>
    </joint>

    <link name="imu_link">
        <visual>
            <geometry>
                <box size="0.05 0.1 0.01"/>
            </geometry>
            <material name="Brown"/>
        </visual>

        <collision>
            <geometry>
                <box size="0.05 0.1 0.01"/>
            </geometry>            
        </collision>

        <xacro:inertial_box mass="0.1" length="0.05" width="0.1" height="0.1">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>    
        
    </link>

</robot>